<table>
    <tr>
        <th>ID</th>
        <td>{{$note->id}}</td>
    </tr>
    <tr>
        <th>Title</th>
        <td>{{$note->title}}</td>
    </tr>
    <tr>
        <th>Content</th>
        <td>{{$note->content}}</td>
    </tr>
</table>
